### ISSUE TITLE
用户部门关联查询FUND_IN_SET函数

### ISSUE THREAD

**Issue by xieyingvs** [yangzongzhuan/RuoYi-Oracle#5]
SysUserMapper.xml中 selectUserList方法中FUND_IN_SET函数报错，是不是需要修改下，oracle可能不支持这个函数。

**Comment by 591st66y** [comment]
https://gitee.com/y_project/RuoYi/issues/I1FEST

**Comment by yangzongzhuan** [comment]
sql脚本里面有FUND_IN_SET函数，刷一下就好。
