### ISSUE TITLE
关于用户自动退出问题

### ISSUE THREAD

**Issue by LieLight** [yangzongzhuan/RuoYi-Oracle#6]
作者，你好，我发现登陆账号后，如果打开过诸如编辑之类的窗口后，会生成新的sessionid，如果此时我再点击其他菜单或按钮会因为找不到这个sessionid而强制登出。不知道你或者其他人是否有遇到相同的问题，望告知

**Comment by yangzongzhuan** [comment]
试了下没有你说的问题哦，也没有人反馈过这种问题。
